---
# roles/hostname/tasks/main.yml
- name: add config/environments directory
  become: yes
  file: path={{ config_path }}/environments \
        owner={{ deploy_user }} group={{ deploy_group }} state=directory

- name: add shared config/environments/production.rb
  become: yes
  template: src=production.rb.j2 dest={{ config_path }}/environments/production.rb \
            owner={{ deploy_user }} group={{ deploy_group }} backup=no
