- name: provision basic alex2 vagrant box
  hosts: vagrant
  remote_user: vagrant
  vars:
    capistrano_user: vagrant
    capistrano_group: vagrant
    # Add keys to the list below for anyone who will cap deploy to the vm
    # see http://docs.ansible.com/ansible/authorized_key_module.html
    deploy_user: deploy
    deploy_group: deploy
    deploy_keys:
      - keyfile: "{{ lookup('env', 'IDENTITY') }}.pub"
    project_dir: /opt
    project_name: alex2
    install_path: "{{ project_dir }}/install"
    rails_env: production
    server_name: 127.0.0.1
    config_path: "{{ project_dir }}/{{ project_name }}/shared/config"
    solr_context: hydra
  roles:
    #- { role: vagrant, sudo: yes }
    - { role: housekeeping, sudo: yes }
    - { role: ruby }
    - { role: hydra-stack }
    - { role: services }
    #- { role: ffmpeg }
    #- { role: imagemagick }
    - { role: passenger, sudo: yes }
    - { role: marmotta }
    - { role: app-config, sudo: yes }
    - { role: ezid }
    - { role: smtp }
    - { role: ldap }
    - { role: hostname }
    - { role: deploy, repo: "https://github.library.ucsb.edu/ADRL/alexandria.git" }
    - { role: sshd }
