---
- include: ldconfig.yml

- name: download ffmpeg
  command: curl -L https://ffmpeg.org/releases/ffmpeg-{{ ffmpeg_ver }}.tar.bz2 \
           -o "{{ install_path }}/ffmpeg-{{ ffmpeg_ver }}.tar.bz2"
  args:
    creates: "{{ install_path }}/ffmpeg-{{ ffmpeg_ver }}.tar.bz2"

- name: checksum ffmpeg tarball
  command: sha256sum ffmpeg-{{ ffmpeg_ver }}.tar.bz2
  args:
    chdir: "{{ install_path }}"
  register: ffmpeg_checksum

- name: verify ffmpeg checksum
  fail: msg="The ffmpeg checksum is incorrect ({{ ffmpeg_checksum.stdout }} instead of {{ ffmpeg_256 }})"
  when: ffmpeg_checksum.stdout != "{{ ffmpeg_256 }}  ffmpeg-{{ ffmpeg_ver }}.tar.bz2"

- name: unpack ffmpeg
  unarchive:
    copy: no
    src: "{{ install_path }}/ffmpeg-{{ ffmpeg_ver }}.tar.bz2"
    dest: "{{ ffmpeg_path }}"

- name: configure ffmpeg
  environment:
    PKG_CONFIG_PATH: /usr/local/lib/pkgconfig
  shell: ./configure --extra-libs="-ldl" --enable-gpl --enable-nonfree --enable-libfdk_aac --enable-libmp3lame --enable-libopus --enable-libvorbis --enable-libvpx --enable-libx264
  args:
    chdir: "{{ ffmpeg_path }}/ffmpeg-{{ ffmpeg_ver }}"

- name: make ffmpeg
  command: make
  args:
    chdir: "{{ ffmpeg_path }}/ffmpeg-{{ ffmpeg_ver }}"

- name: install ffmpeg
  become: yes
  command: make install
  args:
    chdir: "{{ ffmpeg_path }}/ffmpeg-{{ ffmpeg_ver }}"

- name: clean the ffmpeg source tree
  become: yes
  command: make distclean
  args:
    chdir: "{{ ffmpeg_path }}/ffmpeg-{{ ffmpeg_ver }}"

- include: ldconfig.yml
