---
- name: download fdk-aac source
  command: curl -L https://downloads.sourceforge.net/project/opencore-amr/fdk-aac/fdk-aac-{{ fdk_ver }}.tar.gz \
           -o "{{ install_path }}/fdk-aac-{{ fdk_ver }}.tar.gz"
  args:
    creates: "{{ install_path }}/fdk-aac-{{ fdk_ver }}.tar.gz"

- name: checksum fdk-aac source
  command: sha256sum fdk-aac-{{ fdk_ver }}.tar.gz
  args:
    chdir: "{{ install_path }}"
  register: fdk_checksum

- name: verify fdk-aac checksum
  fail: msg="The fdk-aac checksum is incorrect ({{ fdk_checksum.stdout }} instead of {{ fdk_256 }})"
  when: fdk_checksum.stdout != "{{ fdk_256 }} fdk-aac-{{ fdk_ver }}.tar.gz"

- name: unpack fdk-aac source
  unarchive:
    copy: no
    src: "{{ install_path }}/fdk-aac-{{ fdk_ver }}.tar.gz"
    dest: "{{ ffmpeg_path }}"

- name: generate the configure script
  command: ./autogen.sh
  args:
    chdir: "{{ ffmpeg_path }}/fdk-aac-{{ fdk_ver }}"

- name: configure fdk-aac
  command: ./configure --disable-shared --prefix=/usr/local
  args:
    chdir: "{{ ffmpeg_path }}/fdk-aac-{{ fdk_ver }}"
    creates: "{{ ffmpeg_path }}/fdk-aac/Makefile"

- name: make fdk-aac
  command: make
  args:
    chdir: "{{ ffmpeg_path }}/fdk-aac-{{ fdk_ver }}"

- name: install fdk-aac
  become: yes
  command: make install
  args:
    chdir: "{{ ffmpeg_path }}/fdk-aac-{{ fdk_ver }}"

- name: clean the fkd-aac repo
  become: yes
  command: make distclean
  args:
    chdir: "{{ ffmpeg_path }}/fdk-aac-{{ fdk_ver }}"

- include: ldconfig.yml
