---
- name: download libvpx source
  command: curl -L https://github.com/webmproject/libvpx/archive/v{{ vpx_ver }}.tar.gz \
           -o "{{ install_path }}/libvpx-{{ vpx_ver }}.tar.gz"
  args:
    creates: "{{ install_path }}/libvpx-{{ vpx_ver }}.tar.gz"

- name: checksum libvpx source
  command: sha256sum libvpx-{{ vpx_ver }}.tar.gz
  args:
    chdir: "{{ install_path }}"
  register: vpx_checksum

- name: verify libvpx checksum
  fail: msg="The libvpx checksum is incorrect ({{ vpx_checksum.stdout }} instead of {{ vpx_256 }})"
  when: vpx_checksum.stdout != "{{ vpx_256 }}  libvpx-{{ vpx_ver }}.tar.gz"

- name: unpack libvpx
  unarchive:
    copy: no
    src: "{{ install_path }}/libvpx-{{ vpx_ver }}.tar.gz"
    dest: "{{ ffmpeg_path }}"

- name: configure libvpx
  command: ./configure --disable-examples --prefix=/usr/local
  args:
    chdir: "{{ ffmpeg_path }}/libvpx-{{ vpx_ver }}"
    creates: "{{ ffmpeg_path }}/libvpx-{{ vpx_ver }}/Makefile"

- name: make libvpx
  command: make
  args:
    chdir: "{{ ffmpeg_path }}/libvpx-{{ vpx_ver }}"

- name: install libvpx
  become: yes
  command: make install
  args:
    chdir: "{{ ffmpeg_path }}/libvpx-{{ vpx_ver }}"

- name: clean the libvpx repo
  become: yes
  command: make distclean
  args:
    chdir: "{{ ffmpeg_path }}/libvpx-{{ vpx_ver }}"

- include: ldconfig.yml
