---
- name: debug
  shell: whoami
  register: user

- name: what user am I
  debug: var=user

- name: download yasm source
  command: curl -L https://www.tortall.net/projects/yasm/releases/yasm-{{ yasm_ver }}.tar.gz \
           -o "{{ install_path }}/yasm-{{ yasm_ver }}.tar.gz"
  args:
    creates: "{{ install_path }}/yasm-{{ yasm_ver }}.tar.gz"

- name: checksum yasm source
  command: sha256sum yasm-{{ fdk_ver }}.tar.gz
  args:
    chdir: "{{ install_path }}"
  register: yasm_checksum

- name: verify yasm checksum
  fail: msg="The yasm checksum is incorrect ({{ yasm_checksum.stdout }} instead of {{ yasm_256 }})"
  when: yasm_checksum.stdout != "{{ yasm_256 }} yasm-{{ yasm_ver }}.tar.gz"

- name: unpack yasm source
  unarchive:
    copy: no
    src: "{{ install_path }}/yasm-{{ yasm_ver }}.tar.gz"
    dest: "{{ ffmpeg_path }}"

- name: configure yasm
  command: ./configure --prefix=/usr/local
  args:
    chdir: "{{ ffmpeg_path }}/yasm-{{ yasm_ver }}"

- name: make yasm
  command: make
  args:
    chdir: "{{ ffmpeg_path }}/yasm-{{ yasm_ver }}"

- name: install yasm
  become: yes
  command: make install
  args:
    chdir: "{{ ffmpeg_path }}/yasm-{{ yasm_ver }}"

- name: clean the yasm repo
  become: yes
  command: make distclean
  args:
    chdir: "{{ ffmpeg_path }}/yasm-{{ yasm_ver }}"

- include: ldconfig.yml
