---
# ImageMagick regularly removes old tarballs, so use a mirror
- name: download ImageMagick
  command: curl -L https://dl.bintray.com/homebrew/mirror/ImageMagick-{{ imagemagick_ver }}.tar.xz \
           -o "{{ magick_path }}/ImageMagick-{{ imagemagick_ver }}.tar.xz"
  args:
    creates: "{{ magick_path }}/ImageMagick-{{ imagemagick_ver }}.tar.xz"

- name: checksum imagemagick source
  command: sha256sum ImageMagick-{{ imagemagick_ver }}.tar.xz
  args:
    chdir: "{{ magick_path }}"
  register: magick_checksum

- name: verify ImageMagick checksum
  fail: msg="The ImageMagick checksum is incorrect ({{ magick_checksum.stdout }} instead of {{ imagemagick_256 }})"
  when: magick_checksum.stdout != "{{ imagemagick_256 }} ImageMagick-{{ imagemagick_ver }}.tar.xz"

- name: unpack ImageMagick
  unarchive:
    src: "{{ magick_path }}/ImageMagick-{{ imagemagick_ver }}.tar.xz"
    dest: "{{ magick_path }}/"
    copy: no

- name: configure ImageMagick
  environment:
    PKG_CONFIG_PATH: /usr/local/lib/pkgconfig
  command: ./configure --prefix=/usr/local --with-modules=yes
  args:
    chdir: "{{ magick_path }}/ImageMagick-{{ imagemagick_ver }}"

- name: make ImageMagick
  command: make
  args:
    chdir: "{{ magick_path }}/ImageMagick-{{ imagemagick_ver }}"

- name: install ImageMagick
  become: yes
  command: make install
  args:
    chdir: "{{ magick_path }}/ImageMagick-{{ imagemagick_ver }}"

- include: ldconfig.yml
