---
- name: download libpng source
  command: curl -L https://downloads.sourceforge.net/project/libpng/libpng{{ libpng_major }}/{{ libpng_ver }}/libpng-{{ libpng_ver }}.tar.xz \
           -o "{{ magick_path }}/libpng-{{ libpng_ver }}.tar.xz"
  args:
    creates: "{{ magick_path }}/libpng-{{ libpng_ver }}.tar.xz"

- name: checksum libpng source
  command: sha256sum libpng-{{ libpng_ver }}.tar.xz
  args:
    chdir: "{{ magick_path }}"
  register: png_checksum

- name: verify libpng checksum
  fail: msg="The libpng checksum is incorrect ({{ png_checksum.stdout }} instead of {{ libpng_256 }})"
  when: png_checksum.stdout != "{{ libpng_256 }}  libpng-{{ libpng_ver }}.tar.xz"

- name: unzip libpng source
  unarchive:
    src: "{{ magick_path }}/libpng-{{ libpng_ver }}.tar.xz"
    dest: "{{ magick_path }}/"
    creates: "{{ magick_path }}/libpng-{{ libpng_ver }}"
    copy: no

- name: configure libpng
  command: ./configure
  args:
    chdir: "{{ magick_path }}/libpng-{{ libpng_ver }}"

- name: make libpng
  command: make
  args:
    chdir: "{{ magick_path }}/libpng-{{ libpng_ver }}"

- name: install libpng
  become: yes
  command: make install
  args:
    chdir: "{{ magick_path }}/libpng-{{ libpng_ver }}"

- include: ldconfig.yml
