---
- name: download openjpeg source
  command: curl -L https://downloads.sourceforge.net/project/openjpeg.mirror/{{ openjpg_ver }}/openjpeg-{{ openjpg_ver }}.tar.gz \
           -o "{{ magick_path }}/openjpeg-{{ openjpg_ver }}.tar.gz"
  args:
    creates: "{{ magick_path }}/openjpeg-{{ openjpg_ver }}.tar.gz"

- name: checksum openjpeg source
  command: sha256sum openjpeg-{{ openjpg_ver }}.tar.gz
  args:
    chdir: "{{ magick_path }}"
  register: jpeg_checksum

- name: verify openjpeg checksum
  fail: msg="The openjpeg checksum is incorrect ({{ jpeg_checksum.stdout }} instead of {{ openjpg_256 }})"
  when: jpeg_checksum.stdout != "{{ openjpg_256 }}  openjpeg-{{ openjpg_ver }}.tar.gz"

- name: unzip openjpg source
  unarchive:
    src: "{{ magick_path }}/openjpeg-{{ openjpg_ver }}.tar.gz"
    dest: "{{ magick_path }}/"
    creates: "{{ magick_path }}/openjpeg-version.{{ openjpg_ver }}"
    copy: no

- name: configure openjpg
  command: cmake .
  args:
    chdir: "{{ magick_path }}/openjpeg-{{ openjpg_ver }}"

- name: make openjpg
  command: make
  args:
    chdir: "{{ magick_path }}/openjpeg-{{ openjpg_ver }}"

- name: install openjpg
  become: yes
  command:  make install
  args:
    chdir: "{{ magick_path }}/openjpeg-{{ openjpg_ver }}"

- include: ldconfig.yml
