---
- name: create velocity log
  sudo: yes
  file: path=/var/log/tomcat/velocity.log state=touch owner=tomcat group=tomcat mode=0644

- name: symlink velocity log
  sudo: yes
  file: src=/var/log/tomcat/velocity.log dest=/var/lib/tomcat/velocity.log state=link

- name: download solr tarball
  get_url: url=http://archive.apache.org/dist/lucene/solr/{{ solr_ver }}/solr-{{ solr_ver }}.tgz \
           dest={{ install_path }}/solr-{{ solr_ver }}.tgz \
           force=no sha256sum={{ solr_sha }}

- name: untar solr tarball
  unarchive: src={{ install_path }}/solr-{{ solr_ver }}.tgz dest={{ install_path }}/ creates={{ install_path }}/solr-{{ solr_ver }}/bin/solr copy=no

- name: check solr dir
  stat: path={{ solr_home }}/lib
  register: solr_dir

- name: make solr lib dir
  file: owner=tomcat group=tomcat state=directory path={{ solr_home }}/lib
  sudo: yes
  when: solr_dir.stat.exists == False

- name: copy over war file
  sudo: yes
  command: cp {{ install_path }}/solr-{{ solr_ver }}/dist/solr-{{ solr_ver }}.war {{ solr_home }}/

- name: copy over dist dir
  sudo: yes
  shell: cp -r {{ install_path }}/solr-{{ solr_ver }}/dist {{ solr_home }}/lib/

- name: copy over contrib dir
  sudo: yes
  command: cp -r {{ install_path }}/solr-{{ solr_ver }}/contrib {{ solr_home }}/lib/

- name: copy over example collection
  sudo: yes
  command: cp -r --remove-destination {{ install_path }}/solr-{{ solr_ver }}/example/solr/collection1 {{ solr_home }}/

- name: copy logging jars
  sudo: yes
  shell: cp {{ install_path }}/solr-{{ solr_ver }}/example/lib/ext/*.jar {{ tomcat }}/lib/

- name: copy solr-cell jar for text extraction
  sudo: yes
  shell: cp {{ install_path }}/solr-{{ solr_ver }}/dist/solr-cell-{{ solr_ver }}.jar {{ solr_home }}/lib/contrib/extraction/lib/

- name: set ownership and group for solr
  sudo: yes
  shell: chown -R tomcat:tomcat {{ solr_home }}

- name: copy log4j properties file
  sudo: yes
  shell: cp {{ install_path }}/solr-{{ solr_ver }}/example/resources/log4j.properties /usr/share/java/tomcat/

- name: set ownership and group for tomcat
  sudo: yes
  shell: chown -R tomcat:tomcat {{ tomcat }}

- name: create solr xml file
  sudo: yes
  template: src=hydra.xml.j2 dest={{ solr_home }}/{{ solr_context }}.xml group=tomcat owner=tomcat

- name: symlink solr xml file to tomcat
  sudo: yes
  file: src={{ solr_home }}/{{ solr_context }}.xml dest=/etc/tomcat/Catalina/localhost/{{ solr_context }}.xml state=link

- name: create schema file
  sudo: yes
  copy: src=schema.xml dest={{ solr_home }}/collection1/conf/schema.xml group=tomcat owner=tomcat backup=yes

- name: create solrconfig file
  sudo: yes
  copy: src=solrconfig.xml dest={{ solr_home }}/collection1/conf/solrconfig.xml backup=yes
