---
- name: install zip utility
  sudo: yes
  yum: name=unzip state=present

- name: download fits zip
  get_url: url=http://projects.iq.harvard.edu/files/fits/files/fits-{{ fits_ver }}.zip \
           owner={{ ansible_ssh_user }} group={{ ansible_ssh_user }} \
           sha256sum={{ fits_sha }}
           dest={{ install_path }}/fits-{{ fits_ver }}.zip

- name: unpack fits
  unarchive: src={{ install_path }}/fits-{{ fits_ver }}.zip dest={{ install_path }}/ creates={{ install_path }}/fits-{{ fits_ver }}/fits.sh copy=no

- name: make fits executable
  sudo: yes
  file: path={{ install_path }}/fits-{{ fits_ver }}/fits.sh mode=0755

- name: copy fits
  sudo: yes
  shell: cp -r {{ install_path }}/fits-{{ fits_ver }}/* /usr/local/bin/

- name: symlink fits
  sudo: yes
  file: src=/usr/local/bin/fits.sh dest=/usr/local/bin/fits state=link
